### Проверка куки на токен
GET http://localhost:5000/user

### Регистрация нового пользователя
POST http://localhost:5000/user/create-new
Content-Type: application/json

{
    "email": "requests rest 2",
    "password": "1234"
}

### Выход пользователя (удаляем токен из куки)
POST http://localhost:5000/logout

### Войти в систему
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "12345@12345.ru",
    "password": "12345"
}

### Получение всех наборов пользователя
GET http://localhost:5000/sets/


### Создание нового набора у пользователя
POST http://localhost:5000/sets/new-set
Content-Type: application/json

{
    "title": "Тестовое название 2 из requests.rest"
}

### Получить информацию о наборе
GET http://localhost:5000/sets/set/625d5e405701f0be2ba6c6df


### Изменить термин
PUT http://localhost:5000/sets/set/term/rename
Content-Type: application/json

{
    "setId": "625d5e405701f0be2ba6c6df",
    "termId": "625eb1ed3ee443a50c4eb7d8",
    "front": "Самый первый термин на русском",
    "back": "Самый первый термин на английском"
}

### Переключение выполнения термина
PUT http://localhost:5000/sets/set/term/toggle-completed
Content-Type: application/json

{
    "setId": "625d5e405701f0be2ba6c6df",
    "termId": "625eb1ed3ee443a50c4eb7d8"
}
