### Проверка куки на токен
GET http://localhost:5000/user

### Регистрация нового пользователя
POST http://localhost:5000/user/create-new
Content-Type: application/json

{
    "email": "requests rest 2",
    "password": "1234"
}

### Выход пользователя (удаляем токен из куки)
POST http://localhost:5000/logout

### Войти в систему
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "12345@12345.ru",
    "password": "12345"
}

### Получение всех наборов пользователя
GET http://localhost:5000/sets/


### Создание нового набора у пользователя
POST http://localhost:5000/sets/new-set
Content-Type: application/json

{
    "title": "Тестовое название 2 из requests.rest"
}

###
GET http://localhost:5000/sets/625d71797f79e7259f60cb2e

